#!/bin/bash -l
# DO NOT EDIT THIS FILE
# ALL MODIFICATIONS THAT ARE NECESSARY CAN BE DONE BY PROVIDING COMMAND LINE PARAMETERS
#
# THIS SCRIPT WILL EXECUTE AS FOLLOWS:
#   ./leaderboard.sh "FIRST" "SECOND"
#
#   $FIRST srun --cpu-freq=2000000-2000000:performance $SECOND ./perf y x
#
# WHERE y AND x ARE FIXED AND YOU CAN ONLY GIVE ADDITIONAL PARAMTERS VIA FRIST AND SECOND, WHICH MIGHT INCLUDE
# THREAD PINNING< NUMA CONTROL OR OMP DIRECTIVES

if ! [[ -e ./test && -e ./perf ]]; then
    echo "Please make sure that your code is compiled and the two binaries ./perf and ./test are present."
fi

if ! [[ $# == 2 ]]; then
    echo "Always call this script with exactely two arguemnts, even if they are empty (\"\")."
    echo ""
    echo -e "\t./leaderboard.sh \"FIRST\" \"SECOND\""
    echo ""
    echo "Then, it will be executed:"
    echo ""
    echo -e "\t FIRST srun -cpu-freq=2000000-2000000:performance SECOND ./perf y x"
    echo ""
    exit 1
fi

FIRST=$1
SECOND=$2

# Run Tests to verify

TEST=$(./test)

if [[ $TEST == *"failed"* ]]; then
    echo "Some tests failed. Fix you program first before running this script again."
fi

# Run performance for some values

echo "Starting tests..."
RUN_1=$(env -S $FIRST srun --cpu-freq=2000000-2000000:performance $SECOND ./perf 20000 2000)
echo "Test 1 done."
RUN_2=$(env -S $FIRST srun --cpu-freq=2000000-2000000:performance $SECOND ./perf 2000 20000)
echo "Test 2 done."
RUN_3=$(env -S $FIRST srun --cpu-freq=2000000-2000000:performance $SECOND ./perf 1000 400000)
echo "Test 3 done."
RUN_4=$(env -S $FIRST srun --cpu-freq=2000000-2000000:performance $SECOND ./perf 12345 9876)
echo "Test 4 done."

# Check integrity

echo "Verifying integrity and printing final score..."
./verify "$RUN_1" "$RUN_2" "$RUN_3" "$RUN_4"

